import React from 'react';
import { storiesOf } from '@storybook/react';

import Button from './Button';

storiesOf("Button", module)
  .add("Primary", () => <Button label="Primary" type="primary" />)
  .add("Danger", () => <Button label="Danger" type="danger" />)
  .add("Success", () => <Button label="Success" type="success" />)
  .add("Warning", () => <Button label="Warning" type="warning" />)
  .add("Default", () => <Button label="Default" type="default" />)
  .add("Primary Lighter", () => <Button label="Primary" type="primary-lighter" />)
  .add("Danger Lighter", () => <Button label="Danger" type="danger-lighter" />)
  .add("Success Lighter", () => <Button label="Success" type="success-lighter" />)
  .add("Warning Lighter", () => <Button label="Warning" type="warning-lighter" />)
  .add("Default Lighter", () => <Button label="Default" type="default-lighter" />)
  .add("Primary Outline", () => <Button label="Primary" type="primary-lighter" outline />)
  .add("Danger Outline", () => <Button label="Danger" type="danger-lighter" outline />)
  .add("Success Outline", () => <Button label="Success" type="success-lighter" outline />)
  .add("Warning Outline", () => <Button label="Warning" type="warning-lighter" outline />)
  .add("Default Outline", () => <Button label="Default" type="default-lighter" outline />)
  .add("Primary Large", () => <Button label="Large" type="primary" large />)
  .add("Danger Large", () => <Button label="Danger" type="danger" large />)
  .add("Success Large", () => <Button label="Success" type="success" large />)
  .add("Warning Large", () => <Button label="Warning" type="warning" large />)
  .add("Defaut Large", () => <Button label="Default" type="default" large />)
  .add("Primary Lighter Large", () => <Button label="Primary" type="primary-lighter" large />)
  .add("Danger Lighter Large", () => <Button label="Danger" type="danger-lighter" large />)
  .add("Success Lighter Large", () => <Button label="Success" type="success-lighter" large />)
  .add("Warning Lighter Large", () => <Button label="Warning" type="warning-lighter" large />)
  .add("Default Lighter Large", () => <Button label="Default" type="default-lighter" large />)
  .add("Primary Outline Large", () => <Button label="Primary" type="primary-lighter" large outline />)
  .add("Danger Outline Large", () => <Button label="Danger" type="danger-lighter" large outline />)
  .add("Success Outline Large", () => <Button label="Success" type="success-lighter" large outline />)
  .add("Warning Outline Large", () => <Button label="Warning" type="warning-lighter" large outline />)
  .add("Default Outline Large", () => <Button label="Default" type="default-lighter" large outline />)
  .add("Add To Cart", () => <Button label="Add To Cart" type="cart" cartimage />)
  .add("Add To Favorites", () => <Button label="Add To Favorites" type="cart" heartimage />);